cursor                  #FFFFFF
cursor_text_color       background

cursor_shape block

cursor_shape_unfocused hollow

url_color               #7898FB
url_style straight

visual_bell_color       #ff3299
bell_border_color       #ff3299


single_window_padding_width 30


active_border_color     #ff3299
inactive_border_color   #303030



foreground              #CFCFCF
background              #000000
selection_foreground    #EEFFFF
selection_background    #101010

# black
color0 #000000
color8 #4A4A4A

# red
color1 #F07178
color9 #ef6169

# green
color2 #13CA91
color10 #14dbbb

# yellow
color3 #FDF200
color11 #f1e600

# blue
color4 #66ffdd
color12 #9fffea

# magenta
color5 #ff3299
color13 #b7005c

# cyan
color6 #79ffe1
color14 #c3f3e5

# white
color7 #EEFFFF
color15 #FFFFFF
