font_family      Cartograph CF Bold
bold_font        Cartograph CF Bold
italic_font      Cartograph CF Fixed Italic
bold_italic_font Cartograph CF Fixed Bold Italic

font_size 11.0

include current-theme.conf

map Alt+w       copy_to_clipboard

map Ctrl+y       paste_from_clipboard
