backend = "glx"
shadow = true
vsync = true
corner-radius = 0
fading = true
inactive-dim = 0.05
unredir-if-possible = false;
shadow-exclude = [
  "class_g = 'firefox' && argb"
]
# menu        = { shadow = false; };
dropdown_menu = { shadow = false; };
popup_menu    = { shadow = false; };
utility       = { shadow = false; };

fade-in-step = 0.15
fade-out-step = 0.15
