#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP-1 -d I II III IV V
bspc monitor DP-1 -d VI VII VIII X IX

bspc config border_width                  0
bspc config window_gap                   12
bspc config pointer_action1 resize_side

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc rule -a '*' state=pseudo_tiled
bspc rule -a 'Firefox' state=tiling
bspc rule -a 'emacs' state=tiling
bspc rule -a 'pinentry*' state=floating

bspc config normal_border_color "#ffffff"
bspc config focused_border_color "#000000"

exec ~/.screenlayout/laptop.sh &
exec ./batterycheck.sh &
exec picom -b &
exec notify-send -a "BSPWM" -u low  -t 10000 "Happy hacking!" -i "/home/jovo/Pictures/Chan/JagNärJagÄterFrukostPåTisdagMorgonOchHarHurMycketTidSomHelstEftersomDetärSovmorgon.jpg" "Bspwm has started" &
exec feh --bg-fill /home/jovo/Documents/Chan/wallpapers/LightmodeWallpaper.png --bg-fill ~/Pictures/Chan/Black.jpg &
exec mpDris2 &

# Redshift  for Stockholm, Sweden
# exec redshift -P -l 59.334591:18.063240 -t 6600:4500 &

# Redshift for Taipei, the Republic of China
exec redshift -P -l 25.0330:121.5654 -t 6600:4500 &
exec eww -c ~/.config/eww daemon &
exec eww -c ~/.config/eww open bar &
